[build]
  command = "npm install --include=optional && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"
  NPM_FLAGS = "--include=optional"
  # Exclude documentation files from secrets scanning
  SECRETS_SCAN_OMIT_PATHS = "*.md,*.txt,NETLIFY-*.md,*-README.md,*-GUIDE.md,*-DOCUMENTATION.md,.env.example"

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for JS files
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for CSS files
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for 3D model files
[[headers]]
  for = "/planet/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# SPA fallback - redirect only when file doesn't exist
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
